/* Generated by JSIL v0.8.2 build 30762. See http://jsil.org/ for more information. */ 
'use strict';
var $asm02 = JSIL.DeclareAssembly("CSharpXamlForHtml5.System.ServiceModel.dll, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");

JSIL.DeclareNamespace("System");
JSIL.DeclareNamespace("System.ServiceModel");
JSIL.DeclareNamespace("System.ServiceModel.Channels");
/* class System.ServiceModel.Channels.AddressHeader */ 

(function AddressHeader$Members () {
  var $, $thisType;
  function AddressHeader__ctor () {
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Object"), 
      Name: "System.ServiceModel.Channels.AddressHeader", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:false}, ".ctor", 
      JSIL.MethodSignature.Void, 
      AddressHeader__ctor
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class System.ServiceModel.Channels.Binding */ 

(function Binding$Members () {
  var $, $thisType;
  function Binding__ctor () {
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Object"), 
      Name: "System.ServiceModel.Channels.Binding", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      Binding__ctor
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class System.ServiceModel.HttpBindingBase */ 

(function HttpBindingBase$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.ServiceModel.Channels.Binding)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm06.System.Int64)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm06.System.Int32)) ();
  };

  function HttpBindingBase__ctor () {
    $T00().prototype['_ctor'].call(this);
  };

  function HttpBindingBase_get_MaxBufferPoolSize () {
    return this.HttpBindingBase$MaxBufferPoolSize$value;
  };

  function HttpBindingBase_get_MaxBufferSize () {
    return this.HttpBindingBase$MaxBufferSize$value;
  };

  function HttpBindingBase_get_MaxReceivedMessageSize () {
    return this.HttpBindingBase$MaxReceivedMessageSize$value;
  };

  function HttpBindingBase_set_MaxBufferPoolSize (value) {
    this.HttpBindingBase$MaxBufferPoolSize$value = value;
  };

  function HttpBindingBase_set_MaxBufferSize (value) {
    this.HttpBindingBase$MaxBufferSize$value = (value | 0);
  };

  function HttpBindingBase_set_MaxReceivedMessageSize (value) {
    this.HttpBindingBase$MaxReceivedMessageSize$value = value;
  };

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.ServiceModel.Channels.Binding"), 
      Name: "System.ServiceModel.HttpBindingBase", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:false}, ".ctor", 
      JSIL.MethodSignature.Void, 
      HttpBindingBase__ctor
    );

    $.Method({Static:false, Public:true }, "get_MaxBufferPoolSize", 
      JSIL.MethodSignature.Return($.Int64), 
      HttpBindingBase_get_MaxBufferPoolSize
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_MaxBufferSize", 
      JSIL.MethodSignature.Return($.Int32), 
      HttpBindingBase_get_MaxBufferSize
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_MaxReceivedMessageSize", 
      JSIL.MethodSignature.Return($.Int64), 
      HttpBindingBase_get_MaxReceivedMessageSize
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_MaxBufferPoolSize", 
      JSIL.MethodSignature.Action($.Int64), 
      HttpBindingBase_set_MaxBufferPoolSize
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_MaxBufferSize", 
      JSIL.MethodSignature.Action($.Int32), 
      HttpBindingBase_set_MaxBufferSize
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_MaxReceivedMessageSize", 
      JSIL.MethodSignature.Action($.Int64), 
      HttpBindingBase_set_MaxReceivedMessageSize
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $['Field']({Static:false, Public:false}, "HttpBindingBase$MaxBufferPoolSize$value", $.Int64)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "HttpBindingBase$MaxBufferSize$value", $.Int32)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "HttpBindingBase$MaxReceivedMessageSize$value", $.Int64)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Property({Static:false, Public:true }, "MaxBufferPoolSize", $.Int64);

    $.Property({Static:false, Public:true }, "MaxBufferSize", $.Int32);

    $.Property({Static:false, Public:true }, "MaxReceivedMessageSize", $.Int64);

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class System.ServiceModel.BasicHttpBinding */ 

(function BasicHttpBinding$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.ServiceModel.HttpBindingBase)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.System.ServiceModel.BasicHttpSecurityMode)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.System.ServiceModel.BasicHttpSecurity)) ();
  };

  function BasicHttpBinding__ctor$00 () {
    $T00().prototype['_ctor'].call(this);
  };

  function BasicHttpBinding__ctor$01 (securityMode) {
    $T00().prototype['_ctor'].call(this);
    var basicHttpSecurity = new ($T02())();
    basicHttpSecurity.BasicHttpSecurity$Mode$value = securityMode;
    this.BasicHttpBinding$Security$value = basicHttpSecurity;
  };

  function BasicHttpBinding_get_Security () {
    return this.BasicHttpBinding$Security$value;
  };

  function BasicHttpBinding_set_Security (value) {
    this.BasicHttpBinding$Security$value = value;
  };

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.ServiceModel.HttpBindingBase"), 
      Name: "System.ServiceModel.BasicHttpBinding", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      BasicHttpBinding__ctor$00
    );

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.ServiceModel.BasicHttpSecurityMode")), 
      BasicHttpBinding__ctor$01
    );

    $.Method({Static:false, Public:true }, "get_Security", 
      JSIL.MethodSignature.Return($asm02.TypeRef("System.ServiceModel.BasicHttpSecurity")), 
      BasicHttpBinding_get_Security
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Security", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.ServiceModel.BasicHttpSecurity")), 
      BasicHttpBinding_set_Security
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $['Field']({Static:false, Public:false}, "BasicHttpBinding$Security$value", $asm02.TypeRef("System.ServiceModel.BasicHttpSecurity"))
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Property({Static:false, Public:true }, "Security", $asm02.TypeRef("System.ServiceModel.BasicHttpSecurity"));

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class System.ServiceModel.BasicHttpSecurity */ 

(function BasicHttpSecurity$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.ServiceModel.BasicHttpSecurityMode)) ();
  };

  function BasicHttpSecurity__ctor () {
  };

  function BasicHttpSecurity_get_Mode () {
    return this.BasicHttpSecurity$Mode$value;
  };

  function BasicHttpSecurity_set_Mode (value) {
    this.BasicHttpSecurity$Mode$value = value;
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Object"), 
      Name: "System.ServiceModel.BasicHttpSecurity", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      BasicHttpSecurity__ctor
    );

    $.Method({Static:false, Public:true }, "get_Mode", 
      JSIL.MethodSignature.Return($asm02.TypeRef("System.ServiceModel.BasicHttpSecurityMode")), 
      BasicHttpSecurity_get_Mode
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Mode", 
      JSIL.MethodSignature.Action($asm02.TypeRef("System.ServiceModel.BasicHttpSecurityMode")), 
      BasicHttpSecurity_set_Mode
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $['Field']({Static:false, Public:false}, "BasicHttpSecurity$Mode$value", $asm02.TypeRef("System.ServiceModel.BasicHttpSecurityMode"))
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Property({Static:false, Public:true }, "Mode", $asm02.TypeRef("System.ServiceModel.BasicHttpSecurityMode"));

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* enum System.ServiceModel.BasicHttpSecurityMode */ 

JSIL.MakeEnum(
  {
    FullName: "System.ServiceModel.BasicHttpSecurityMode", 
    BaseType: $asm06.TypeRef("System.Int32"), 
    IsPublic: true, 
    IsFlags: false, 
  }, 
  {
    None: 0, 
    Transport: 1, 
  }
);

/* class System.ServiceModel.EndpointAddress */ 

(function EndpointAddress$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm01.System.Uri)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize(System.Array.Of($asm02.System.ServiceModel.Channels.AddressHeader))) ();
  };

  function EndpointAddress__ctor (uri, addressHeaders) {
    this._uri = uri;
  };

  function EndpointAddress_get_Uri () {
    return this._uri;
  };

  function EndpointAddress_set_Uri (value) {
    this._uri = value;
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Object"), 
      Name: "System.ServiceModel.EndpointAddress", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 2, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      new JSIL.MethodSignature(null, [$asm01.TypeRef("System.Uri"), $jsilcore.TypeRef("System.Array", [$asm02.TypeRef("System.ServiceModel.Channels.AddressHeader")])]), 
      EndpointAddress__ctor
    )
      .Parameter(1, "addressHeaders", function (_) {
          _.Attribute($asm06.TypeRef("System.ParamArrayAttribute"))
        });

    $.Method({Static:false, Public:true }, "get_Uri", 
      JSIL.MethodSignature.Return($asm01.TypeRef("System.Uri")), 
      EndpointAddress_get_Uri
    );

    $.Method({Static:false, Public:false}, "set_Uri", 
      JSIL.MethodSignature.Action($asm01.TypeRef("System.Uri")), 
      EndpointAddress_set_Uri
    );

    $['Field']({Static:false, Public:false}, "_uri", $asm01.TypeRef("System.Uri")); 
    $.Property({Static:false, Public:true }, "Uri", $asm01.TypeRef("System.Uri"));

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class System.ServiceModel.FaultException */ 

(function FaultException$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm06.System.Exception)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm06.System.String)) ();
  };

  function FaultException__ctor$00 () {
    $T00().prototype['_ctor'].call(this);
  };

  function FaultException__ctor$01 (reason) {
    $T00().prototype['_ctor'].call(this);
    this._message = reason;
  };

  function FaultException_get_Message () {
    return this._message;
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Exception"), 
      Name: "System.ServiceModel.FaultException", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      FaultException__ctor$00
    );

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($.String), 
      FaultException__ctor$01
    );

    $.Method({Static:false, Public:true , Virtual:true }, "get_Message", 
      JSIL.MethodSignature.Return($.String), 
      FaultException_get_Message
    );

    $['Field']({Static:false, Public:false}, "_message", $.String); 
    $.Property({Static:false, Public:true , Virtual:true }, "Message", $.String);

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* interface System.ServiceModel.IClientChannel */ 

JSIL.MakeInterface(
  "System.ServiceModel.IClientChannel", true, [], function ($) {
    $.Method({}, "get_AllowInitializationUI", JSIL.MethodSignature.Return($.Boolean));
    $.Method({}, "set_AllowInitializationUI", JSIL.MethodSignature.Action($.Boolean));
    $.Method({}, "get_DidInteractiveInitialization", JSIL.MethodSignature.Return($.Boolean));
    $.Method({}, "get_Via", JSIL.MethodSignature.Return($asm01.TypeRef("System.Uri")));
    $.Method({}, "BeginDisplayInitializationUI", new JSIL.MethodSignature($asm06.TypeRef("System.IAsyncResult"), [$asm06.TypeRef("System.AsyncCallback"), $.Object]));
    $.Method({}, "DisplayInitializationUI", JSIL.MethodSignature.Void);
    $.Method({}, "EndDisplayInitializationUI", JSIL.MethodSignature.Action($asm06.TypeRef("System.IAsyncResult")));
    $.Property({}, "AllowInitializationUI");
    $.Property({}, "DidInteractiveInitialization");
    $.Property({}, "Via");
  }, [$asm06.TypeRef("System.IDisposable")]);

/* class System.ServiceModel.MessageContractMemberAttribute */ 

(function MessageContractMemberAttribute$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm06.System.Attribute)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm06.System.Boolean)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm06.System.String)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm01.System.Net.Security.ProtectionLevel)) ();
  };

  function MessageContractMemberAttribute__ctor () {
    $T00().prototype['_ctor'].call(this);
  };

  function MessageContractMemberAttribute_get_HasProtectionLevel () {
    return this.MessageContractMemberAttribute$HasProtectionLevel$value;
  };

  function MessageContractMemberAttribute_get_Name () {
    return this.MessageContractMemberAttribute$Name$value;
  };

  function MessageContractMemberAttribute_get_Namespace () {
    return this.MessageContractMemberAttribute$Namespace$value;
  };

  function MessageContractMemberAttribute_get_ProtectionLevel () {
    return this.MessageContractMemberAttribute$ProtectionLevel$value;
  };

  function MessageContractMemberAttribute_set_HasProtectionLevel (value) {
    this.MessageContractMemberAttribute$HasProtectionLevel$value = value;
  };

  function MessageContractMemberAttribute_set_Name (value) {
    this.MessageContractMemberAttribute$Name$value = value;
  };

  function MessageContractMemberAttribute_set_Namespace (value) {
    this.MessageContractMemberAttribute$Namespace$value = value;
  };

  function MessageContractMemberAttribute_set_ProtectionLevel (value) {
    this.MessageContractMemberAttribute$ProtectionLevel$value = value;
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Attribute"), 
      Name: "System.ServiceModel.MessageContractMemberAttribute", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:false}, ".ctor", 
      JSIL.MethodSignature.Void, 
      MessageContractMemberAttribute__ctor
    );

    $.Method({Static:false, Public:true }, "get_HasProtectionLevel", 
      JSIL.MethodSignature.Return($.Boolean), 
      MessageContractMemberAttribute_get_HasProtectionLevel
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Name", 
      JSIL.MethodSignature.Return($.String), 
      MessageContractMemberAttribute_get_Name
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Namespace", 
      JSIL.MethodSignature.Return($.String), 
      MessageContractMemberAttribute_get_Namespace
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_ProtectionLevel", 
      JSIL.MethodSignature.Return($asm01.TypeRef("System.Net.Security.ProtectionLevel")), 
      MessageContractMemberAttribute_get_ProtectionLevel
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "set_HasProtectionLevel", 
      JSIL.MethodSignature.Action($.Boolean), 
      MessageContractMemberAttribute_set_HasProtectionLevel
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Name", 
      JSIL.MethodSignature.Action($.String), 
      MessageContractMemberAttribute_set_Name
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Namespace", 
      JSIL.MethodSignature.Action($.String), 
      MessageContractMemberAttribute_set_Namespace
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_ProtectionLevel", 
      JSIL.MethodSignature.Action($asm01.TypeRef("System.Net.Security.ProtectionLevel")), 
      MessageContractMemberAttribute_set_ProtectionLevel
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $['Field']({Static:false, Public:false}, "MessageContractMemberAttribute$HasProtectionLevel$value", $.Boolean)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "MessageContractMemberAttribute$Name$value", $.String)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "MessageContractMemberAttribute$Namespace$value", $.String)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "MessageContractMemberAttribute$ProtectionLevel$value", $asm01.TypeRef("System.Net.Security.ProtectionLevel"))
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Property({Static:false, Public:true }, "HasProtectionLevel", $.Boolean);

    $.Property({Static:false, Public:true }, "Name", $.String);

    $.Property({Static:false, Public:true }, "Namespace", $.String);

    $.Property({Static:false, Public:true }, "ProtectionLevel", $asm01.TypeRef("System.Net.Security.ProtectionLevel"));

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class System.ServiceModel.MessageBodyMemberAttribute */ 

(function MessageBodyMemberAttribute$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.System.ServiceModel.MessageContractMemberAttribute)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm06.System.Int32)) ();
  };

  function MessageBodyMemberAttribute__ctor () {
    $T00().prototype['_ctor'].call(this);
  };

  function MessageBodyMemberAttribute_get_Order () {
    return this.MessageBodyMemberAttribute$Order$value;
  };

  function MessageBodyMemberAttribute_set_Order (value) {
    this.MessageBodyMemberAttribute$Order$value = (value | 0);
  };

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("System.ServiceModel.MessageContractMemberAttribute"), 
      Name: "System.ServiceModel.MessageBodyMemberAttribute", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      MessageBodyMemberAttribute__ctor
    );

    $.Method({Static:false, Public:true }, "get_Order", 
      JSIL.MethodSignature.Return($.Int32), 
      MessageBodyMemberAttribute_get_Order
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Order", 
      JSIL.MethodSignature.Action($.Int32), 
      MessageBodyMemberAttribute_set_Order
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $['Field']({Static:false, Public:false}, "MessageBodyMemberAttribute$Order$value", $.Int32)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Property({Static:false, Public:true }, "Order", $.Int32);

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm06.TypeRef("System.AttributeUsageAttribute"), function () { return [$asm06.System.AttributeTargets.$Flags("Field", "Property")]; });

})();

/* class System.ServiceModel.MessageContractAttribute */ 

(function MessageContractAttribute$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm06.System.Attribute)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm06.System.Boolean)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm01.System.Net.Security.ProtectionLevel)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm06.System.String)) ();
  };

  function MessageContractAttribute__ctor () {
    $T00().prototype['_ctor'].call(this);
  };

  function MessageContractAttribute_get_HasProtectionLevel () {
    return this.MessageContractAttribute$HasProtectionLevel$value;
  };

  function MessageContractAttribute_get_IsWrapped () {
    return this.MessageContractAttribute$IsWrapped$value;
  };

  function MessageContractAttribute_get_ProtectionLevel () {
    return this.MessageContractAttribute$ProtectionLevel$value;
  };

  function MessageContractAttribute_get_WrapperName () {
    return this.MessageContractAttribute$WrapperName$value;
  };

  function MessageContractAttribute_get_WrapperNamespace () {
    return this.MessageContractAttribute$WrapperNamespace$value;
  };

  function MessageContractAttribute_set_HasProtectionLevel (value) {
    this.MessageContractAttribute$HasProtectionLevel$value = value;
  };

  function MessageContractAttribute_set_IsWrapped (value) {
    this.MessageContractAttribute$IsWrapped$value = value;
  };

  function MessageContractAttribute_set_ProtectionLevel (value) {
    this.MessageContractAttribute$ProtectionLevel$value = value;
  };

  function MessageContractAttribute_set_WrapperName (value) {
    this.MessageContractAttribute$WrapperName$value = value;
  };

  function MessageContractAttribute_set_WrapperNamespace (value) {
    this.MessageContractAttribute$WrapperNamespace$value = value;
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Attribute"), 
      Name: "System.ServiceModel.MessageContractAttribute", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      MessageContractAttribute__ctor
    );

    $.Method({Static:false, Public:true }, "get_HasProtectionLevel", 
      JSIL.MethodSignature.Return($.Boolean), 
      MessageContractAttribute_get_HasProtectionLevel
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_IsWrapped", 
      JSIL.MethodSignature.Return($.Boolean), 
      MessageContractAttribute_get_IsWrapped
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_ProtectionLevel", 
      JSIL.MethodSignature.Return($asm01.TypeRef("System.Net.Security.ProtectionLevel")), 
      MessageContractAttribute_get_ProtectionLevel
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_WrapperName", 
      JSIL.MethodSignature.Return($.String), 
      MessageContractAttribute_get_WrapperName
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_WrapperNamespace", 
      JSIL.MethodSignature.Return($.String), 
      MessageContractAttribute_get_WrapperNamespace
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "set_HasProtectionLevel", 
      JSIL.MethodSignature.Action($.Boolean), 
      MessageContractAttribute_set_HasProtectionLevel
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_IsWrapped", 
      JSIL.MethodSignature.Action($.Boolean), 
      MessageContractAttribute_set_IsWrapped
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_ProtectionLevel", 
      JSIL.MethodSignature.Action($asm01.TypeRef("System.Net.Security.ProtectionLevel")), 
      MessageContractAttribute_set_ProtectionLevel
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_WrapperName", 
      JSIL.MethodSignature.Action($.String), 
      MessageContractAttribute_set_WrapperName
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_WrapperNamespace", 
      JSIL.MethodSignature.Action($.String), 
      MessageContractAttribute_set_WrapperNamespace
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $['Field']({Static:false, Public:false}, "MessageContractAttribute$HasProtectionLevel$value", $.Boolean)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "MessageContractAttribute$IsWrapped$value", $.Boolean)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "MessageContractAttribute$ProtectionLevel$value", $asm01.TypeRef("System.Net.Security.ProtectionLevel"))
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "MessageContractAttribute$WrapperName$value", $.String)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "MessageContractAttribute$WrapperNamespace$value", $.String)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Property({Static:false, Public:true }, "HasProtectionLevel", $.Boolean);

    $.Property({Static:false, Public:true }, "IsWrapped", $.Boolean);

    $.Property({Static:false, Public:true }, "ProtectionLevel", $asm01.TypeRef("System.Net.Security.ProtectionLevel"));

    $.Property({Static:false, Public:true }, "WrapperName", $.String);

    $.Property({Static:false, Public:true }, "WrapperNamespace", $.String);

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm06.TypeRef("System.AttributeUsageAttribute"), function () { return [$asm06.System.AttributeTargets.$Flags("Class", "Struct")]; });

})();

/* class System.ServiceModel.OperationContractAttribute */ 

(function OperationContractAttribute$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm06.System.Attribute)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm06.System.String)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm06.System.Boolean)) ();
  };

  function OperationContractAttribute__ctor () {
    $T00().prototype['_ctor'].call(this);
  };

  function OperationContractAttribute_get_Action () {
    return this.OperationContractAttribute$Action$value;
  };

  function OperationContractAttribute_get_AsyncPattern () {
    return this.OperationContractAttribute$AsyncPattern$value;
  };

  function OperationContractAttribute_get_IsOneWay () {
    return this.OperationContractAttribute$IsOneWay$value;
  };

  function OperationContractAttribute_get_Name () {
    return this.OperationContractAttribute$Name$value;
  };

  function OperationContractAttribute_get_ReplyAction () {
    return this.OperationContractAttribute$ReplyAction$value;
  };

  function OperationContractAttribute_set_Action (value) {
    this.OperationContractAttribute$Action$value = value;
  };

  function OperationContractAttribute_set_AsyncPattern (value) {
    this.OperationContractAttribute$AsyncPattern$value = value;
  };

  function OperationContractAttribute_set_IsOneWay (value) {
    this.OperationContractAttribute$IsOneWay$value = value;
  };

  function OperationContractAttribute_set_Name (value) {
    this.OperationContractAttribute$Name$value = value;
  };

  function OperationContractAttribute_set_ReplyAction (value) {
    this.OperationContractAttribute$ReplyAction$value = value;
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Attribute"), 
      Name: "System.ServiceModel.OperationContractAttribute", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      OperationContractAttribute__ctor
    );

    $.Method({Static:false, Public:true }, "get_Action", 
      JSIL.MethodSignature.Return($.String), 
      OperationContractAttribute_get_Action
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_AsyncPattern", 
      JSIL.MethodSignature.Return($.Boolean), 
      OperationContractAttribute_get_AsyncPattern
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_IsOneWay", 
      JSIL.MethodSignature.Return($.Boolean), 
      OperationContractAttribute_get_IsOneWay
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Name", 
      JSIL.MethodSignature.Return($.String), 
      OperationContractAttribute_get_Name
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_ReplyAction", 
      JSIL.MethodSignature.Return($.String), 
      OperationContractAttribute_get_ReplyAction
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Action", 
      JSIL.MethodSignature.Action($.String), 
      OperationContractAttribute_set_Action
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_AsyncPattern", 
      JSIL.MethodSignature.Action($.Boolean), 
      OperationContractAttribute_set_AsyncPattern
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_IsOneWay", 
      JSIL.MethodSignature.Action($.Boolean), 
      OperationContractAttribute_set_IsOneWay
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Name", 
      JSIL.MethodSignature.Action($.String), 
      OperationContractAttribute_set_Name
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_ReplyAction", 
      JSIL.MethodSignature.Action($.String), 
      OperationContractAttribute_set_ReplyAction
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $['Field']({Static:false, Public:false}, "OperationContractAttribute$Action$value", $.String)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "OperationContractAttribute$AsyncPattern$value", $.Boolean)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "OperationContractAttribute$IsOneWay$value", $.Boolean)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "OperationContractAttribute$Name$value", $.String)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "OperationContractAttribute$ReplyAction$value", $.String)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Property({Static:false, Public:true }, "Action", $.String);

    $.Property({Static:false, Public:true }, "AsyncPattern", $.Boolean);

    $.Property({Static:false, Public:true }, "IsOneWay", $.Boolean);

    $.Property({Static:false, Public:true }, "Name", $.String);

    $.Property({Static:false, Public:true }, "ReplyAction", $.String);

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm06.TypeRef("System.AttributeUsageAttribute"), function () { return [$asm06.System.AttributeTargets.Method]; });

})();

/* class System.ServiceModel.ServiceContractAttribute */ 

(function ServiceContractAttribute$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm06.System.Attribute)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm06.System.Type)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm06.System.String)) ();
  };

  function ServiceContractAttribute__ctor () {
    $T00().prototype['_ctor'].call(this);
    this.ServiceContractAttribute$Namespace$value = "http://tempuri.org";
  };

  function ServiceContractAttribute_get_CallbackContract () {
    return this.ServiceContractAttribute$CallbackContract$value;
  };

  function ServiceContractAttribute_get_ConfigurationName () {
    return this.ServiceContractAttribute$ConfigurationName$value;
  };

  function ServiceContractAttribute_get_Name () {
    return this.ServiceContractAttribute$Name$value;
  };

  function ServiceContractAttribute_get_Namespace () {
    return this.ServiceContractAttribute$Namespace$value;
  };

  function ServiceContractAttribute_set_CallbackContract (value) {
    this.ServiceContractAttribute$CallbackContract$value = value;
  };

  function ServiceContractAttribute_set_ConfigurationName (value) {
    this.ServiceContractAttribute$ConfigurationName$value = value;
  };

  function ServiceContractAttribute_set_Name (value) {
    this.ServiceContractAttribute$Name$value = value;
  };

  function ServiceContractAttribute_set_Namespace (value) {
    this.ServiceContractAttribute$Namespace$value = value;
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Attribute"), 
      Name: "System.ServiceModel.ServiceContractAttribute", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      ServiceContractAttribute__ctor
    );

    $.Method({Static:false, Public:true }, "get_CallbackContract", 
      JSIL.MethodSignature.Return($asm06.TypeRef("System.Type")), 
      ServiceContractAttribute_get_CallbackContract
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_ConfigurationName", 
      JSIL.MethodSignature.Return($.String), 
      ServiceContractAttribute_get_ConfigurationName
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Name", 
      JSIL.MethodSignature.Return($.String), 
      ServiceContractAttribute_get_Name
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "get_Namespace", 
      JSIL.MethodSignature.Return($.String), 
      ServiceContractAttribute_get_Namespace
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_CallbackContract", 
      JSIL.MethodSignature.Action($asm06.TypeRef("System.Type")), 
      ServiceContractAttribute_set_CallbackContract
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_ConfigurationName", 
      JSIL.MethodSignature.Action($.String), 
      ServiceContractAttribute_set_ConfigurationName
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Name", 
      JSIL.MethodSignature.Action($.String), 
      ServiceContractAttribute_set_Name
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:true }, "set_Namespace", 
      JSIL.MethodSignature.Action($.String), 
      ServiceContractAttribute_set_Namespace
    )
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $['Field']({Static:false, Public:false}, "ServiceContractAttribute$CallbackContract$value", $asm06.TypeRef("System.Type"))
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "ServiceContractAttribute$ConfigurationName$value", $.String)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "ServiceContractAttribute$Name$value", $.String)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $['Field']({Static:false, Public:false}, "ServiceContractAttribute$Namespace$value", $.String)
      .Attribute($asm06.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute")); 
    $.Property({Static:false, Public:true }, "CallbackContract", $asm06.TypeRef("System.Type"));

    $.Property({Static:false, Public:true }, "ConfigurationName", $.String);

    $.Property({Static:false, Public:true }, "Name", $.String);

    $.Property({Static:false, Public:true }, "Namespace", $.String);

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  })
    .Attribute($asm06.TypeRef("System.AttributeUsageAttribute"), function () { return [$asm06.System.AttributeTargets.$Flags("Class", "Interface")]; });

})();

