/* Generated by JSIL v0.8.2 build 30762. See http://jsil.org/ for more information. */ 
'use strict';
var $asm07 = JSIL.DeclareAssembly("SampleCalculatorApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");

JSIL.DeclareNamespace("SampleCalculatorApp1");
/* class SampleCalculatorApp1.App */ 

(function App$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm00.Windows.UI.Xaml.Application)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm07.SampleCalculatorApp1.MainPage)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm00.Windows.UI.Xaml.Window)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm00.Windows.UI.Xaml.ResourceDictionary)) ();
  };

  function App__ctor () {
    $T00().prototype['_ctor'].call(this);
    this['InitializeComponent']();
    var mainPage = new ($T01())();
    $T02().Window$Current$value['set_Content'](mainPage);
  };

  function App_InitializeComponent () {
    if (!this._contentLoaded) {
      this._contentLoaded = true;
      var ResourceDictionary_7b6ce214959d4c6b9be835d4e168ae4d = new ($T03())();
      this.Application$Resources$value = ResourceDictionary_7b6ce214959d4c6b9be835d4e168ae4d;
    }
  };

  JSIL.MakeType({
      BaseType: $asm00.TypeRef("Windows.UI.Xaml.Application"), 
      Name: "SampleCalculatorApp1.App", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      App__ctor
    );

    $.Method({Static:false, Public:false}, "InitializeComponent", 
      JSIL.MethodSignature.Void, 
      App_InitializeComponent
    );

    $['Field']({Static:false, Public:false}, "_contentLoaded", $.Boolean); 
    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SampleCalculatorApp1.MainPage */ 

(function MainPage$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Page)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.TextBlock)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm07.SampleCalculatorApp1.PaperTrail)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm06.System.Char)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm06.System.String)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm06.System.Int32)) ();
  };
  var $T06 = function () {
    return ($T06 = JSIL.Memoize($asm07.SampleCalculatorApp1.MainPage_Operation)) ();
  };
  var $T07 = function () {
    return ($T07 = JSIL.Memoize($asm06.System.Exception)) ();
  };
  var $T08 = function () {
    return ($T08 = JSIL.Memoize($asm06.System.Double)) ();
  };
  var $T09 = function () {
    return ($T09 = JSIL.Memoize($asm06.System.Convert)) ();
  };
  var $T0A = function () {
    return ($T0A = JSIL.Memoize($asm06.System.Math)) ();
  };
  var $T0B = function () {
    return ($T0B = JSIL.Memoize($asm06.System.Object)) ();
  };
  var $T0C = function () {
    return ($T0C = JSIL.Memoize($asm00.Windows.UI.Xaml.RoutedEventArgs)) ();
  };
  var $T0D = function () {
    return ($T0D = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.ContentControl)) ();
  };
  var $T0E = function () {
    return ($T0E = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Button)) ();
  };
  var $T0F = function () {
    return ($T0F = JSIL.Memoize(System.Array.Of($asm06.System.Char))) ();
  };
  var $T10 = function () {
    return ($T10 = JSIL.Memoize($asm00.Windows.UI.Xaml.Style)) ();
  };
  var $T11 = function () {
    return ($T11 = JSIL.Memoize($asm00.Windows.UI.Xaml.Setter)) ();
  };
  var $T12 = function () {
    return ($T12 = JSIL.Memoize($asm00.Windows.UI.Xaml.FrameworkElement)) ();
  };
  var $T13 = function () {
    return ($T13 = JSIL.Memoize($asm00.DotNetForHtml5.Core.TypeFromStringConverters)) ();
  };
  var $T14 = function () {
    return ($T14 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Control)) ();
  };
  var $T15 = function () {
    return ($T15 = JSIL.Memoize($asm00.Windows.UI.Xaml.Media.Brush)) ();
  };
  var $T16 = function () {
    return ($T16 = JSIL.Memoize($asm06.System.Collections.ObjectModel.Collection$b1.Of($asm00.Windows.UI.Xaml.Setter))) ();
  };
  var $T17 = function () {
    return ($T17 = JSIL.Memoize($asm00.Windows.UI.Xaml.ResourceDictionary)) ();
  };
  var $T18 = function () {
    return ($T18 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.ScrollViewer)) ();
  };
  var $T19 = function () {
    return ($T19 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.ScrollBarVisibility)) ();
  };
  var $T1A = function () {
    return ($T1A = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Canvas)) ();
  };
  var $T1B = function () {
    return ($T1B = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Panel)) ();
  };
  var $T1C = function () {
    return ($T1C = JSIL.Memoize($asm00.Windows.UI.Xaml.HorizontalAlignment)) ();
  };
  var $T1D = function () {
    return ($T1D = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Border)) ();
  };
  var $T1E = function () {
    return ($T1E = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.UserControl)) ();
  };
  var $T1F = function () {
    return ($T1F = JSIL.Memoize($asm00.Windows.UI.Xaml.Thickness)) ();
  };
  var $T20 = function () {
    return ($T20 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.Primitives.ButtonBase)) ();
  };
  var $T21 = function () {
    return ($T21 = JSIL.Memoize($asm00.Windows.UI.Xaml.RoutedEventHandler)) ();
  };
  var $T22 = function () {
    return ($T22 = JSIL.Memoize($asm00.System.Windows.Markup.StaticResource)) ();
  };
  var $T23 = function () {
    return ($T23 = JSIL.Memoize($asm06.System.Collections.ObjectModel.Collection$b1.Of($asm00.Windows.UI.Xaml.UIElement))) ();
  };
  var $T24 = function () {
    return ($T24 = JSIL.Memoize($asm06.System.Collections.Generic.List$b1.Of($asm06.System.Object))) ();
  };
  var $T25 = function () {
    return ($T25 = JSIL.Memoize($asm03.System.Windows.Markup.MarkupExtension)) ();
  };
  var $T26 = function () {
    return ($T26 = JSIL.Memoize($asm00.System.ServiceProvider)) ();
  };
  var $T27 = function () {
    return ($T27 = JSIL.Memoize($asm06.System.Boolean)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.ConstructorSignature($asm07.TypeRef("SampleCalculatorApp1.PaperTrail"), [$asm00.TypeRef("Windows.UI.Xaml.Controls.TextBlock")]))) ();
  };
  var $S01 = function () {
    return ($S01 = JSIL.Memoize(new JSIL.MethodSignature($asm06.TypeRef("System.Double"), [$asm06.TypeRef("System.String")]))) ();
  };
  var $S02 = function () {
    return ($S02 = JSIL.Memoize(new JSIL.ConstructorSignature($asm06.TypeRef("System.Exception"), [$asm06.TypeRef("System.String")]))) ();
  };
  var $S03 = function () {
    return ($S03 = JSIL.Memoize(new JSIL.ConstructorSignature($asm00.TypeRef("Windows.UI.Xaml.Style"), null))) ();
  };
  var $S04 = function () {
    return ($S04 = JSIL.Memoize(new JSIL.ConstructorSignature($asm00.TypeRef("Windows.UI.Xaml.Setter"), null))) ();
  };
  var $S05 = function () {
    return ($S05 = JSIL.Memoize(new JSIL.ConstructorSignature($asm00.TypeRef("System.Windows.Markup.StaticResource"), null))) ();
  };
  var $S06 = function () {
    return ($S06 = JSIL.Memoize(new JSIL.ConstructorSignature($asm06.TypeRef("System.Collections.Generic.List`1", [$asm06.TypeRef("System.Object")]), null))) ();
  };

  function MainPage__ctor () {
    this._display = "";
    $T00().prototype['_ctor'].call(this);
    this['InitializeComponent']();
    this.PaperBox = new ($T01())();
    this.Paper = $S00().Construct(this.PaperBox);
    this['ProcessKey']("0");
    this['set_EraseDisplay'](true);
  };

  function MainPage_AddToDisplay (c) {
    if ((c['charCodeAt'](0) | 0) === ((".")['charCodeAt'](0) | 0)) {
      if ((this['get_Display']().indexOf(".", 0)) >= 0) {
        return;
      }
      this['set_Display'](JSIL.ConcatString(this['get_Display'](), c));
    } else if (!(((c['charCodeAt'](0) | 0) < (("0")['charCodeAt'](0) | 0)) || ((c['charCodeAt'](0) | 0) > (("9")['charCodeAt'](0) | 0)))) {
      this['set_Display'](JSIL.ConcatString(this['get_Display'](), c));
    } else if ((c['charCodeAt'](0) | 0) === (("\x08")['charCodeAt'](0) | 0)) {
      if ((this['get_Display']().length | 0) <= 1) {
        this['set_Display']($T04().Empty);
      } else {
        var i = (this['get_Display']().length | 0);
        this['set_Display'](System.String.Remove(this['get_Display'](), ((i - 1) | 0), 1));
      }
    }
    this['UpdateDisplay']();
  };

  function MainPage_Calc (LastOper, $exception) {
    var d = 0;
    try {
      switch (LastOper['valueOf']()) {
        case 1: 
          (this.Paper)['AddArguments']($T04()['Format'](
              "{0}\xb7{1}\u207b\xb9", 
              this['get_LastValue'](), 
              this['get_Display']()
            ));
          d = +((+$S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']()) / +$S01().CallStatic($T09(), "ToDouble", null, this['get_Display']())));
          this['CheckResult'](d);
          (this.Paper)['AddResult']((d).toString());
          break;

        case 2: 
          (this.Paper)['AddArguments']($T04()['Format'](
              "{0}*{1}", 
              this['get_LastValue'](), 
              this['get_Display']()
            ));
          d = +$S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']()) * +$S01().CallStatic($T09(), "ToDouble", null, this['get_Display']());
          this['CheckResult'](d);
          (this.Paper)['AddResult']((d).toString());
          break;

        case 3: 
          (this.Paper)['AddArguments']($T04()['Format'](
              "{0}-{1}", 
              this['get_LastValue'](), 
              this['get_Display']()
            ));
          d = +$S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']()) - +$S01().CallStatic($T09(), "ToDouble", null, this['get_Display']());
          this['CheckResult'](d);
          (this.Paper)['AddResult']((d).toString());
          break;

        case 4: 
          (this.Paper)['AddArguments']($T04()['Format'](
              "{0}+{1}", 
              this['get_LastValue'](), 
              this['get_Display']()
            ));
          d = +$S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']()) + +$S01().CallStatic($T09(), "ToDouble", null, this['get_Display']());
          this['CheckResult'](d);
          (this.Paper)['AddResult']((d).toString());
          break;

        case 5: 
          (this.Paper)['AddArguments']($T04()['Format']("\u221a{0}", this['get_LastValue']()));
          d = (Math.sqrt($S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']())));
          this['CheckResult'](d);
          (this.Paper)['AddResult']((d).toString());
          break;

        case 6: 
          (this.Paper)['AddArguments']($T04()['Format']("1/{0}", this['get_LastValue']()));
          d = +((1 / +$S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']())));
          this['CheckResult'](d);
          (this.Paper)['AddResult']((d).toString());
          break;

        case 7: 
          d = +$S01().CallStatic($T09(), "ToDouble", null, this['get_LastValue']()) * -1;
          break;

      }
    } catch ($exception) {
      d = 0;
      (this.DisplayBox)['set_Text']("Error");
    }
    return d;
  };

  function MainPage_CalcResults () {
    if (this.LastOper !== $T06().None) {
      this['set_Display']((this['Calc'](this.LastOper)).toString());
      this['UpdateDisplay']();
    }
  };

  function MainPage_CheckResult (d) {
    if (isNaN(d)) {
      throw $S02().Construct("Illegal value");
    }
  };

  function MainPage_DigitBtn_Click (sender, e) {
    var s = (($T0E().$Cast(sender))['get_Content']())['toString']();
    var ids = (JSIL.StringToCharArray(s));
    this['ProcessKey'](ids[0]);
  };

  function MainPage_get_Display () {
    return this._display;
  };

  function MainPage_get_EraseDisplay () {
    return this._erasediplay;
  };

  function MainPage_get_LastValue () {
    if (this._last_val == $T04().Empty) {
      var result = "0";
    } else {
      result = this._last_val;
    }
    return result;
  };

  function MainPage_InitializeComponent () {
    if (!this._contentLoaded) {
      this._contentLoaded = true;
      var Style_fd77afe7dfb0430bbc1b05a8ef25fe5d = $S03().Construct();
      Style_fd77afe7dfb0430bbc1b05a8ef25fe5d['set_TargetType']($T0E().__Type__);
      var Setter_394dcd29a8a843e3b619bb33bf5649a4 = $S04().Construct();
      Setter_394dcd29a8a843e3b619bb33bf5649a4['set_Property']($T12().HeightProperty);
      Setter_394dcd29a8a843e3b619bb33bf5649a4['set_Value']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "60")));
      var Setter_f23e40a06caf46b49570704b86cf33f4 = $S04().Construct();
      Setter_f23e40a06caf46b49570704b86cf33f4['set_Property']($T12().WidthProperty);
      Setter_f23e40a06caf46b49570704b86cf33f4['set_Value']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "60")));
      var Setter_7878ee4a4f45472fb6b01b861506d5a6 = $S04().Construct();
      Setter_7878ee4a4f45472fb6b01b861506d5a6['set_Property']($T14().ForegroundProperty);
      Setter_7878ee4a4f45472fb6b01b861506d5a6['set_Value']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FFBBBBBB")));
      var Setter_b4d012f2b7ca4757827922d1cc740b23 = $S04().Construct();
      Setter_b4d012f2b7ca4757827922d1cc740b23['set_Property']($T14().FontSizeProperty);
      Setter_b4d012f2b7ca4757827922d1cc740b23['set_Value']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "18")));
      (Style_fd77afe7dfb0430bbc1b05a8ef25fe5d['get_Setters']())['Add'](Setter_394dcd29a8a843e3b619bb33bf5649a4);
      (Style_fd77afe7dfb0430bbc1b05a8ef25fe5d['get_Setters']())['Add'](Setter_f23e40a06caf46b49570704b86cf33f4);
      (Style_fd77afe7dfb0430bbc1b05a8ef25fe5d['get_Setters']())['Add'](Setter_7878ee4a4f45472fb6b01b861506d5a6);
      (Style_fd77afe7dfb0430bbc1b05a8ef25fe5d['get_Setters']())['Add'](Setter_b4d012f2b7ca4757827922d1cc740b23);
      (this['get_Resources']())['Add']("ButtonStyle", Style_fd77afe7dfb0430bbc1b05a8ef25fe5d);
      var ScrollViewer_756e7e0917c34861b90c3232c63e6466 = new ($T18())();
      ScrollViewer_756e7e0917c34861b90c3232c63e6466['set_HorizontalScrollBarVisibility']($T19().Auto);
      ScrollViewer_756e7e0917c34861b90c3232c63e6466['set_VerticalScrollBarVisibility']($T19().Auto);
      ScrollViewer_756e7e0917c34861b90c3232c63e6466['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "Black")));
      var Canvas_bec4b478b06a41a6a913089291d95389 = new ($T1A())();
      Canvas_bec4b478b06a41a6a913089291d95389['set_Height']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "415")));
      Canvas_bec4b478b06a41a6a913089291d95389['set_Width']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "320")));
      Canvas_bec4b478b06a41a6a913089291d95389['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF161616")));
      Canvas_bec4b478b06a41a6a913089291d95389['set_HorizontalAlignment']($T1C().Center);
      var Border_1399f340eba14be9becbc02e9bb94316 = new ($T1D())();
      Border_1399f340eba14be9becbc02e9bb94316['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF222222")));
      $T1A()['SetLeft'](Border_1399f340eba14be9becbc02e9bb94316, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "0")));
      $T1A()['SetTop'](Border_1399f340eba14be9becbc02e9bb94316, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "0")));
      Border_1399f340eba14be9becbc02e9bb94316['set_Width']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "320")));
      Border_1399f340eba14be9becbc02e9bb94316['set_Height']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "82")));
      var TextBlock_e6b424b21de248a0b9b54bfa06022ba7 = new ($T01())();
      $T1E().prototype['RegisterName'].call(this, "DisplayBox", TextBlock_e6b424b21de248a0b9b54bfa06022ba7);
      TextBlock_e6b424b21de248a0b9b54bfa06022ba7['set_Name']("DisplayBox");
      TextBlock_e6b424b21de248a0b9b54bfa06022ba7['set_Text']("23.5");
      TextBlock_e6b424b21de248a0b9b54bfa06022ba7['set_Foreground']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FFBBBBBB")));
      TextBlock_e6b424b21de248a0b9b54bfa06022ba7['set_FontSize']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "32")));
      TextBlock_e6b424b21de248a0b9b54bfa06022ba7['set_HorizontalAlignment']($T1C().Right);
      (TextBlock_e6b424b21de248a0b9b54bfa06022ba7.Margin = $T1F().$Cast($T13()['ConvertFromInvariantString']($T1F().__Type__, "0,10,10,0"))['MemberwiseClone']());
      Border_1399f340eba14be9becbc02e9bb94316['set_Child'](TextBlock_e6b424b21de248a0b9b54bfa06022ba7);
      var Button_4c057217c7104c16b95a724b7c91b06e = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BC", Button_4c057217c7104c16b95a724b7c91b06e);
      Button_4c057217c7104c16b95a724b7c91b06e['set_Name']("BC");
      Button_4c057217c7104c16b95a724b7c91b06e['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_4c057217c7104c16b95a724b7c91b06e['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF125166")));
      Button_4c057217c7104c16b95a724b7c91b06e['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "C"));
      $T1A()['SetTop'](Button_4c057217c7104c16b95a724b7c91b06e, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "87")));
      var StaticResource_071b69b678f840a0af146a3701f17cd6 = $S05().Construct();
      StaticResource_071b69b678f840a0af146a3701f17cd6.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_bf4760120113491aa536f542c6d525f0 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BCE", Button_bf4760120113491aa536f542c6d525f0);
      Button_bf4760120113491aa536f542c6d525f0['set_Name']("BCE");
      Button_bf4760120113491aa536f542c6d525f0['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_bf4760120113491aa536f542c6d525f0['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF2C2C2C")));
      Button_bf4760120113491aa536f542c6d525f0['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "CE"));
      $T1A()['SetTop'](Button_bf4760120113491aa536f542c6d525f0, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "152")));
      var StaticResource_73b133a02b024adca00a29e1175a8701 = $S05().Construct();
      StaticResource_73b133a02b024adca00a29e1175a8701.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_c40fcbeaa733470093fa9acf1158796a = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B7", Button_c40fcbeaa733470093fa9acf1158796a);
      Button_c40fcbeaa733470093fa9acf1158796a['set_Name']("B7");
      Button_c40fcbeaa733470093fa9acf1158796a['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_c40fcbeaa733470093fa9acf1158796a['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_c40fcbeaa733470093fa9acf1158796a['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "7"));
      $T1A()['SetLeft'](Button_c40fcbeaa733470093fa9acf1158796a, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "65")));
      $T1A()['SetTop'](Button_c40fcbeaa733470093fa9acf1158796a, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "87")));
      var StaticResource_adf7df93a7014972b88752824d1150aa = $S05().Construct();
      StaticResource_adf7df93a7014972b88752824d1150aa.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_96516dde79d9468e9a711f6361702f80 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B8", Button_96516dde79d9468e9a711f6361702f80);
      Button_96516dde79d9468e9a711f6361702f80['set_Name']("B8");
      Button_96516dde79d9468e9a711f6361702f80['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_96516dde79d9468e9a711f6361702f80['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_96516dde79d9468e9a711f6361702f80['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "8"));
      $T1A()['SetLeft'](Button_96516dde79d9468e9a711f6361702f80, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "130")));
      $T1A()['SetTop'](Button_96516dde79d9468e9a711f6361702f80, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "87")));
      var StaticResource_f9236868025045759587b5a43082ded5 = $S05().Construct();
      StaticResource_f9236868025045759587b5a43082ded5.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_4698e3e49f6549af9feacf98f10b73b9 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B9", Button_4698e3e49f6549af9feacf98f10b73b9);
      Button_4698e3e49f6549af9feacf98f10b73b9['set_Name']("B9");
      Button_4698e3e49f6549af9feacf98f10b73b9['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_4698e3e49f6549af9feacf98f10b73b9['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_4698e3e49f6549af9feacf98f10b73b9['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "9"));
      $T1A()['SetLeft'](Button_4698e3e49f6549af9feacf98f10b73b9, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "195")));
      $T1A()['SetTop'](Button_4698e3e49f6549af9feacf98f10b73b9, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "87")));
      var StaticResource_af4548ab584e4f0dbcda032ad64e5ce = $S05().Construct();
      StaticResource_af4548ab584e4f0dbcda032ad64e5ce.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_b493091c1f5448acb2959c260c258bac = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B4", Button_b493091c1f5448acb2959c260c258bac);
      Button_b493091c1f5448acb2959c260c258bac['set_Name']("B4");
      Button_b493091c1f5448acb2959c260c258bac['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_b493091c1f5448acb2959c260c258bac['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_b493091c1f5448acb2959c260c258bac['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "4"));
      $T1A()['SetLeft'](Button_b493091c1f5448acb2959c260c258bac, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "65")));
      $T1A()['SetTop'](Button_b493091c1f5448acb2959c260c258bac, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "152")));
      var StaticResource_a8062b0976a3494295deb8fe92107acd = $S05().Construct();
      StaticResource_a8062b0976a3494295deb8fe92107acd.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_2a23da514ebd4b0a99c45df7cfbd866f = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B5", Button_2a23da514ebd4b0a99c45df7cfbd866f);
      Button_2a23da514ebd4b0a99c45df7cfbd866f['set_Name']("B5");
      Button_2a23da514ebd4b0a99c45df7cfbd866f['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_2a23da514ebd4b0a99c45df7cfbd866f['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_2a23da514ebd4b0a99c45df7cfbd866f['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "5"));
      $T1A()['SetLeft'](Button_2a23da514ebd4b0a99c45df7cfbd866f, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "130")));
      $T1A()['SetTop'](Button_2a23da514ebd4b0a99c45df7cfbd866f, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "152")));
      var StaticResource_f9184b59cc18481fa1538202c5bac832 = $S05().Construct();
      StaticResource_f9184b59cc18481fa1538202c5bac832.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_eba8318ee4484e65b7ecb4b9d44f375 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B6", Button_eba8318ee4484e65b7ecb4b9d44f375);
      Button_eba8318ee4484e65b7ecb4b9d44f375['set_Name']("B6");
      Button_eba8318ee4484e65b7ecb4b9d44f375['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_eba8318ee4484e65b7ecb4b9d44f375['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_eba8318ee4484e65b7ecb4b9d44f375['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "6"));
      $T1A()['SetLeft'](Button_eba8318ee4484e65b7ecb4b9d44f375, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "195")));
      $T1A()['SetTop'](Button_eba8318ee4484e65b7ecb4b9d44f375, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "152")));
      var StaticResource_c29f9354ba824816b3c0c1ba8a9035cd = $S05().Construct();
      StaticResource_c29f9354ba824816b3c0c1ba8a9035cd.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_e3d9082a2e5b40a5b60c9ffc19e921b8 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B1", Button_e3d9082a2e5b40a5b60c9ffc19e921b8);
      Button_e3d9082a2e5b40a5b60c9ffc19e921b8['set_Name']("B1");
      Button_e3d9082a2e5b40a5b60c9ffc19e921b8['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_e3d9082a2e5b40a5b60c9ffc19e921b8['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_e3d9082a2e5b40a5b60c9ffc19e921b8['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "1"));
      $T1A()['SetLeft'](Button_e3d9082a2e5b40a5b60c9ffc19e921b8, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "65")));
      $T1A()['SetTop'](Button_e3d9082a2e5b40a5b60c9ffc19e921b8, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "217")));
      var StaticResource_ac53240bc9c24978857f5029234b4ad = $S05().Construct();
      StaticResource_ac53240bc9c24978857f5029234b4ad.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_d37769377e07461a94b294b2bba9374a = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B2", Button_d37769377e07461a94b294b2bba9374a);
      Button_d37769377e07461a94b294b2bba9374a['set_Name']("B2");
      Button_d37769377e07461a94b294b2bba9374a['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_d37769377e07461a94b294b2bba9374a['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_d37769377e07461a94b294b2bba9374a['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "2"));
      $T1A()['SetLeft'](Button_d37769377e07461a94b294b2bba9374a, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "130")));
      $T1A()['SetTop'](Button_d37769377e07461a94b294b2bba9374a, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "217")));
      var StaticResource_21b339437b7645219124f53ba6d19b80 = $S05().Construct();
      StaticResource_21b339437b7645219124f53ba6d19b80.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_cf4d11efbd1b4937bcefb38d2011a465 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B3", Button_cf4d11efbd1b4937bcefb38d2011a465);
      Button_cf4d11efbd1b4937bcefb38d2011a465['set_Name']("B3");
      Button_cf4d11efbd1b4937bcefb38d2011a465['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_cf4d11efbd1b4937bcefb38d2011a465['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_cf4d11efbd1b4937bcefb38d2011a465['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "3"));
      $T1A()['SetLeft'](Button_cf4d11efbd1b4937bcefb38d2011a465, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "195")));
      $T1A()['SetTop'](Button_cf4d11efbd1b4937bcefb38d2011a465, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "217")));
      var StaticResource_26d1a61015aa4add80fff440edc386d = $S05().Construct();
      StaticResource_26d1a61015aa4add80fff440edc386d.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_d87e2525bce241318a453983d8aec861 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "B0", Button_d87e2525bce241318a453983d8aec861);
      Button_d87e2525bce241318a453983d8aec861['set_Name']("B0");
      Button_d87e2525bce241318a453983d8aec861['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_d87e2525bce241318a453983d8aec861['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF3C3C3C")));
      Button_d87e2525bce241318a453983d8aec861['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "0"));
      $T1A()['SetLeft'](Button_d87e2525bce241318a453983d8aec861, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "65")));
      $T1A()['SetTop'](Button_d87e2525bce241318a453983d8aec861, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "282")));
      Button_d87e2525bce241318a453983d8aec861['set_Width']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "126")));
      var StaticResource_8dc18c55327d40e198d886be3c755d0d = $S05().Construct();
      StaticResource_8dc18c55327d40e198d886be3c755d0d.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_e5d6c10c33654865a62a34ae4a668cf8 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BPeriod", Button_e5d6c10c33654865a62a34ae4a668cf8);
      Button_e5d6c10c33654865a62a34ae4a668cf8['set_Name']("BPeriod");
      Button_e5d6c10c33654865a62a34ae4a668cf8['add_Click']($T21()['New'](this, $thisType.prototype['DigitBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "DigitBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_e5d6c10c33654865a62a34ae4a668cf8['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF565656")));
      Button_e5d6c10c33654865a62a34ae4a668cf8['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "."));
      $T1A()['SetLeft'](Button_e5d6c10c33654865a62a34ae4a668cf8, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "195")));
      $T1A()['SetTop'](Button_e5d6c10c33654865a62a34ae4a668cf8, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "282")));
      var StaticResource_a3d0a5d69f4b4b62904fc1311a335c5b = $S05().Construct();
      StaticResource_a3d0a5d69f4b4b62904fc1311a335c5b.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_e3d0235ab6174d3b85e215ea4b53cd29 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BDevide", Button_e3d0235ab6174d3b85e215ea4b53cd29);
      Button_e3d0235ab6174d3b85e215ea4b53cd29['set_Name']("BDevide");
      Button_e3d0235ab6174d3b85e215ea4b53cd29['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_e3d0235ab6174d3b85e215ea4b53cd29['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF2C2C2C")));
      Button_e3d0235ab6174d3b85e215ea4b53cd29['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "/"));
      $T1A()['SetLeft'](Button_e3d0235ab6174d3b85e215ea4b53cd29, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "260")));
      $T1A()['SetTop'](Button_e3d0235ab6174d3b85e215ea4b53cd29, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "87")));
      var StaticResource_92a23dfbb09a4168a6876dc8682ace34 = $S05().Construct();
      StaticResource_92a23dfbb09a4168a6876dc8682ace34.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_1c7279317d4842f7b77e4f49d59d7582 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BMultiply", Button_1c7279317d4842f7b77e4f49d59d7582);
      Button_1c7279317d4842f7b77e4f49d59d7582['set_Name']("BMultiply");
      Button_1c7279317d4842f7b77e4f49d59d7582['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_1c7279317d4842f7b77e4f49d59d7582['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF2C2C2C")));
      Button_1c7279317d4842f7b77e4f49d59d7582['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "*"));
      $T1A()['SetLeft'](Button_1c7279317d4842f7b77e4f49d59d7582, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "260")));
      $T1A()['SetTop'](Button_1c7279317d4842f7b77e4f49d59d7582, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "152")));
      var StaticResource_25268caf86d4429984d1beeee1322ea9 = $S05().Construct();
      StaticResource_25268caf86d4429984d1beeee1322ea9.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_5cfd2939dff04a75adb381bdce3aa11e = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BMinus", Button_5cfd2939dff04a75adb381bdce3aa11e);
      Button_5cfd2939dff04a75adb381bdce3aa11e['set_Name']("BMinus");
      Button_5cfd2939dff04a75adb381bdce3aa11e['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_5cfd2939dff04a75adb381bdce3aa11e['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF2C2C2C")));
      Button_5cfd2939dff04a75adb381bdce3aa11e['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "-"));
      $T1A()['SetLeft'](Button_5cfd2939dff04a75adb381bdce3aa11e, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "260")));
      $T1A()['SetTop'](Button_5cfd2939dff04a75adb381bdce3aa11e, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "217")));
      var StaticResource_f8ddd78fbc2c46e8a0d73b5f55b9cd23 = $S05().Construct();
      StaticResource_f8ddd78fbc2c46e8a0d73b5f55b9cd23.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_1790b4a975fa40b7a286a42302e3b71a = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BPlus", Button_1790b4a975fa40b7a286a42302e3b71a);
      Button_1790b4a975fa40b7a286a42302e3b71a['set_Name']("BPlus");
      Button_1790b4a975fa40b7a286a42302e3b71a['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_1790b4a975fa40b7a286a42302e3b71a['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF2C2C2C")));
      Button_1790b4a975fa40b7a286a42302e3b71a['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "+"));
      $T1A()['SetLeft'](Button_1790b4a975fa40b7a286a42302e3b71a, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "260")));
      $T1A()['SetTop'](Button_1790b4a975fa40b7a286a42302e3b71a, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "282")));
      var StaticResource_78cc96e91d67422aa4877a105b577253 = $S05().Construct();
      StaticResource_78cc96e91d67422aa4877a105b577253.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_aff6175a926c4a709d816186efbd641d = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BEqual", Button_aff6175a926c4a709d816186efbd641d);
      Button_aff6175a926c4a709d816186efbd641d['set_Name']("BEqual");
      Button_aff6175a926c4a709d816186efbd641d['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_aff6175a926c4a709d816186efbd641d['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF125166")));
      Button_aff6175a926c4a709d816186efbd641d['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "="));
      $T1A()['SetLeft'](Button_aff6175a926c4a709d816186efbd641d, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "65")));
      $T1A()['SetTop'](Button_aff6175a926c4a709d816186efbd641d, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "347")));
      Button_aff6175a926c4a709d816186efbd641d['set_Width']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "255")));
      Button_aff6175a926c4a709d816186efbd641d['set_FontSize']($T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "30")));
      var StaticResource_325ac28614e544e7b1fed8f3d58991bd = $S05().Construct();
      StaticResource_325ac28614e544e7b1fed8f3d58991bd.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_137d97ae6e5b49a7821b63e4c92edd64 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BSqrt", Button_137d97ae6e5b49a7821b63e4c92edd64);
      Button_137d97ae6e5b49a7821b63e4c92edd64['set_Name']("BSqrt");
      Button_137d97ae6e5b49a7821b63e4c92edd64['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_137d97ae6e5b49a7821b63e4c92edd64['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "\u221a"));
      Button_137d97ae6e5b49a7821b63e4c92edd64['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF565656")));
      $T1A()['SetTop'](Button_137d97ae6e5b49a7821b63e4c92edd64, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "217")));
      var StaticResource_bec170d3bf2b4a2582a69aa255e9f61e = $S05().Construct();
      StaticResource_bec170d3bf2b4a2582a69aa255e9f61e.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_1167110c760e469eacf303206edc97a0 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BOneOver", Button_1167110c760e469eacf303206edc97a0);
      Button_1167110c760e469eacf303206edc97a0['set_Name']("BOneOver");
      Button_1167110c760e469eacf303206edc97a0['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_1167110c760e469eacf303206edc97a0['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF565656")));
      Button_1167110c760e469eacf303206edc97a0['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "1/x"));
      $T1A()['SetTop'](Button_1167110c760e469eacf303206edc97a0, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "282")));
      var StaticResource_a98bd80c87d34983bd067750d613399b = $S05().Construct();
      StaticResource_a98bd80c87d34983bd067750d613399b.StaticResource$ResourceKey$value = "ButtonStyle";
      var Button_2e03f58259104ffd8b87b9c4129cbb47 = new ($T0E())();
      $T1E().prototype['RegisterName'].call(this, "BPM", Button_2e03f58259104ffd8b87b9c4129cbb47);
      Button_2e03f58259104ffd8b87b9c4129cbb47['set_Name']("BPM");
      Button_2e03f58259104ffd8b87b9c4129cbb47['add_Click']($T21()['New'](this, $thisType.prototype['OperBtn_Click'], function () { return JSIL.GetMethodInfo($thisType, "OperBtn_Click", new JSIL.MethodSignature(null, [$asm06.System.Object, $asm00.Windows.UI.Xaml.RoutedEventArgs]), false); }));
      Button_2e03f58259104ffd8b87b9c4129cbb47['set_Background']($T15().$Cast($T13()['ConvertFromInvariantString']($T15().__Type__, "#FF565656")));
      Button_2e03f58259104ffd8b87b9c4129cbb47['set_Content']($T13()['ConvertFromInvariantString']($T0B().__Type__, "+/-"));
      $T1A()['SetTop'](Button_2e03f58259104ffd8b87b9c4129cbb47, $T08().$Cast($T13()['ConvertFromInvariantString']($T08().__Type__, "347")));
      var StaticResource_1dbfff6d86d84143a1b5808f6616c49e = $S05().Construct();
      StaticResource_1dbfff6d86d84143a1b5808f6616c49e.StaticResource$ResourceKey$value = "ButtonStyle";
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Border_1399f340eba14be9becbc02e9bb94316);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_4c057217c7104c16b95a724b7c91b06e);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_bf4760120113491aa536f542c6d525f0);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_c40fcbeaa733470093fa9acf1158796a);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_96516dde79d9468e9a711f6361702f80);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_4698e3e49f6549af9feacf98f10b73b9);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_b493091c1f5448acb2959c260c258bac);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_2a23da514ebd4b0a99c45df7cfbd866f);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_eba8318ee4484e65b7ecb4b9d44f375);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_e3d9082a2e5b40a5b60c9ffc19e921b8);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_d37769377e07461a94b294b2bba9374a);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_cf4d11efbd1b4937bcefb38d2011a465);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_d87e2525bce241318a453983d8aec861);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_e5d6c10c33654865a62a34ae4a668cf8);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_e3d0235ab6174d3b85e215ea4b53cd29);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_1c7279317d4842f7b77e4f49d59d7582);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_5cfd2939dff04a75adb381bdce3aa11e);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_1790b4a975fa40b7a286a42302e3b71a);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_aff6175a926c4a709d816186efbd641d);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_137d97ae6e5b49a7821b63e4c92edd64);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_1167110c760e469eacf303206edc97a0);
      (Canvas_bec4b478b06a41a6a913089291d95389['get_Children']())['Add'](Button_2e03f58259104ffd8b87b9c4129cbb47);
      ScrollViewer_756e7e0917c34861b90c3232c63e6466['set_Content'](Canvas_bec4b478b06a41a6a913089291d95389);
      this['set_Content'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      this.DisplayBox = TextBlock_e6b424b21de248a0b9b54bfa06022ba7;
      this.BC = Button_4c057217c7104c16b95a724b7c91b06e;
      this.BCE = Button_bf4760120113491aa536f542c6d525f0;
      this.B7 = Button_c40fcbeaa733470093fa9acf1158796a;
      this.B8 = Button_96516dde79d9468e9a711f6361702f80;
      this.B9 = Button_4698e3e49f6549af9feacf98f10b73b9;
      this.B4 = Button_b493091c1f5448acb2959c260c258bac;
      this.B5 = Button_2a23da514ebd4b0a99c45df7cfbd866f;
      this.B6 = Button_eba8318ee4484e65b7ecb4b9d44f375;
      this.B1 = Button_e3d9082a2e5b40a5b60c9ffc19e921b8;
      this.B2 = Button_d37769377e07461a94b294b2bba9374a;
      this.B3 = Button_cf4d11efbd1b4937bcefb38d2011a465;
      this.B0 = Button_d87e2525bce241318a453983d8aec861;
      this.BPeriod = Button_e5d6c10c33654865a62a34ae4a668cf8;
      this.BDevide = Button_e3d0235ab6174d3b85e215ea4b53cd29;
      this.BMultiply = Button_1c7279317d4842f7b77e4f49d59d7582;
      this.BMinus = Button_5cfd2939dff04a75adb381bdce3aa11e;
      this.BPlus = Button_1790b4a975fa40b7a286a42302e3b71a;
      this.BEqual = Button_aff6175a926c4a709d816186efbd641d;
      this.BSqrt = Button_137d97ae6e5b49a7821b63e4c92edd64;
      this.BOneOver = Button_1167110c760e469eacf303206edc97a0;
      this.BPM = Button_2e03f58259104ffd8b87b9c4129cbb47;
      var parents_90f77fec0a114b4984d00afbcf8d395b = $S06().Construct();
      parents_90f77fec0a114b4984d00afbcf8d395b['Add'](Button_4c057217c7104c16b95a724b7c91b06e);
      parents_90f77fec0a114b4984d00afbcf8d395b['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_90f77fec0a114b4984d00afbcf8d395b['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_90f77fec0a114b4984d00afbcf8d395b['Add'](this);
      Button_4c057217c7104c16b95a724b7c91b06e['set_Style']($T10().$Cast(StaticResource_071b69b678f840a0af146a3701f17cd6['ProvideValue'](new ($T26())(Button_4c057217c7104c16b95a724b7c91b06e, null, parents_90f77fec0a114b4984d00afbcf8d395b))));
      var parents_c455216246de4ed6af4fa7bb660d2ab5 = $S06().Construct();
      parents_c455216246de4ed6af4fa7bb660d2ab5['Add'](Button_bf4760120113491aa536f542c6d525f0);
      parents_c455216246de4ed6af4fa7bb660d2ab5['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_c455216246de4ed6af4fa7bb660d2ab5['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_c455216246de4ed6af4fa7bb660d2ab5['Add'](this);
      Button_bf4760120113491aa536f542c6d525f0['set_Style']($T10().$Cast(StaticResource_73b133a02b024adca00a29e1175a8701['ProvideValue'](new ($T26())(Button_bf4760120113491aa536f542c6d525f0, null, parents_c455216246de4ed6af4fa7bb660d2ab5))));
      var parents_029cff75b50e44d09ff53e6806e8400b = $S06().Construct();
      parents_029cff75b50e44d09ff53e6806e8400b['Add'](Button_c40fcbeaa733470093fa9acf1158796a);
      parents_029cff75b50e44d09ff53e6806e8400b['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_029cff75b50e44d09ff53e6806e8400b['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_029cff75b50e44d09ff53e6806e8400b['Add'](this);
      Button_c40fcbeaa733470093fa9acf1158796a['set_Style']($T10().$Cast(StaticResource_adf7df93a7014972b88752824d1150aa['ProvideValue'](new ($T26())(Button_c40fcbeaa733470093fa9acf1158796a, null, parents_029cff75b50e44d09ff53e6806e8400b))));
      var parents_fd796a3396d54c82a3bf6a525e58f957 = $S06().Construct();
      parents_fd796a3396d54c82a3bf6a525e58f957['Add'](Button_96516dde79d9468e9a711f6361702f80);
      parents_fd796a3396d54c82a3bf6a525e58f957['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_fd796a3396d54c82a3bf6a525e58f957['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_fd796a3396d54c82a3bf6a525e58f957['Add'](this);
      Button_96516dde79d9468e9a711f6361702f80['set_Style']($T10().$Cast(StaticResource_f9236868025045759587b5a43082ded5['ProvideValue'](new ($T26())(Button_96516dde79d9468e9a711f6361702f80, null, parents_fd796a3396d54c82a3bf6a525e58f957))));
      var parents_96f8cd89b6144ccdad01e13580511bc8 = $S06().Construct();
      parents_96f8cd89b6144ccdad01e13580511bc8['Add'](Button_4698e3e49f6549af9feacf98f10b73b9);
      parents_96f8cd89b6144ccdad01e13580511bc8['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_96f8cd89b6144ccdad01e13580511bc8['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_96f8cd89b6144ccdad01e13580511bc8['Add'](this);
      Button_4698e3e49f6549af9feacf98f10b73b9['set_Style']($T10().$Cast(StaticResource_af4548ab584e4f0dbcda032ad64e5ce['ProvideValue'](new ($T26())(Button_4698e3e49f6549af9feacf98f10b73b9, null, parents_96f8cd89b6144ccdad01e13580511bc8))));
      var parents_d1c1426cf3e04ffdb5280c06458dea91 = $S06().Construct();
      parents_d1c1426cf3e04ffdb5280c06458dea91['Add'](Button_b493091c1f5448acb2959c260c258bac);
      parents_d1c1426cf3e04ffdb5280c06458dea91['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_d1c1426cf3e04ffdb5280c06458dea91['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_d1c1426cf3e04ffdb5280c06458dea91['Add'](this);
      Button_b493091c1f5448acb2959c260c258bac['set_Style']($T10().$Cast(StaticResource_a8062b0976a3494295deb8fe92107acd['ProvideValue'](new ($T26())(Button_b493091c1f5448acb2959c260c258bac, null, parents_d1c1426cf3e04ffdb5280c06458dea91))));
      var parents_8f14bc11cf9e4d5bb39d84637b9ee194 = $S06().Construct();
      parents_8f14bc11cf9e4d5bb39d84637b9ee194['Add'](Button_2a23da514ebd4b0a99c45df7cfbd866f);
      parents_8f14bc11cf9e4d5bb39d84637b9ee194['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_8f14bc11cf9e4d5bb39d84637b9ee194['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_8f14bc11cf9e4d5bb39d84637b9ee194['Add'](this);
      Button_2a23da514ebd4b0a99c45df7cfbd866f['set_Style']($T10().$Cast(StaticResource_f9184b59cc18481fa1538202c5bac832['ProvideValue'](new ($T26())(Button_2a23da514ebd4b0a99c45df7cfbd866f, null, parents_8f14bc11cf9e4d5bb39d84637b9ee194))));
      var parents_199f7ce91d384bd8ae6af31653bab5d2 = $S06().Construct();
      parents_199f7ce91d384bd8ae6af31653bab5d2['Add'](Button_eba8318ee4484e65b7ecb4b9d44f375);
      parents_199f7ce91d384bd8ae6af31653bab5d2['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_199f7ce91d384bd8ae6af31653bab5d2['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_199f7ce91d384bd8ae6af31653bab5d2['Add'](this);
      Button_eba8318ee4484e65b7ecb4b9d44f375['set_Style']($T10().$Cast(StaticResource_c29f9354ba824816b3c0c1ba8a9035cd['ProvideValue'](new ($T26())(Button_eba8318ee4484e65b7ecb4b9d44f375, null, parents_199f7ce91d384bd8ae6af31653bab5d2))));
      var parents_12d92b9580e145208bffa8cf8de65e12 = $S06().Construct();
      parents_12d92b9580e145208bffa8cf8de65e12['Add'](Button_e3d9082a2e5b40a5b60c9ffc19e921b8);
      parents_12d92b9580e145208bffa8cf8de65e12['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_12d92b9580e145208bffa8cf8de65e12['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_12d92b9580e145208bffa8cf8de65e12['Add'](this);
      Button_e3d9082a2e5b40a5b60c9ffc19e921b8['set_Style']($T10().$Cast(StaticResource_ac53240bc9c24978857f5029234b4ad['ProvideValue'](new ($T26())(Button_e3d9082a2e5b40a5b60c9ffc19e921b8, null, parents_12d92b9580e145208bffa8cf8de65e12))));
      var parents_f9995d6826254022973aad84ba272a18 = $S06().Construct();
      parents_f9995d6826254022973aad84ba272a18['Add'](Button_d37769377e07461a94b294b2bba9374a);
      parents_f9995d6826254022973aad84ba272a18['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_f9995d6826254022973aad84ba272a18['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_f9995d6826254022973aad84ba272a18['Add'](this);
      Button_d37769377e07461a94b294b2bba9374a['set_Style']($T10().$Cast(StaticResource_21b339437b7645219124f53ba6d19b80['ProvideValue'](new ($T26())(Button_d37769377e07461a94b294b2bba9374a, null, parents_f9995d6826254022973aad84ba272a18))));
      var parents_497977dc514244e79fc1e06f9dd43a0d = $S06().Construct();
      parents_497977dc514244e79fc1e06f9dd43a0d['Add'](Button_cf4d11efbd1b4937bcefb38d2011a465);
      parents_497977dc514244e79fc1e06f9dd43a0d['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_497977dc514244e79fc1e06f9dd43a0d['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_497977dc514244e79fc1e06f9dd43a0d['Add'](this);
      Button_cf4d11efbd1b4937bcefb38d2011a465['set_Style']($T10().$Cast(StaticResource_26d1a61015aa4add80fff440edc386d['ProvideValue'](new ($T26())(Button_cf4d11efbd1b4937bcefb38d2011a465, null, parents_497977dc514244e79fc1e06f9dd43a0d))));
      var parents_108545f6b6f24e8aadb663952a4dc492 = $S06().Construct();
      parents_108545f6b6f24e8aadb663952a4dc492['Add'](Button_d87e2525bce241318a453983d8aec861);
      parents_108545f6b6f24e8aadb663952a4dc492['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_108545f6b6f24e8aadb663952a4dc492['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_108545f6b6f24e8aadb663952a4dc492['Add'](this);
      Button_d87e2525bce241318a453983d8aec861['set_Style']($T10().$Cast(StaticResource_8dc18c55327d40e198d886be3c755d0d['ProvideValue'](new ($T26())(Button_d87e2525bce241318a453983d8aec861, null, parents_108545f6b6f24e8aadb663952a4dc492))));
      var parents_f177b45712ba4be0a0d9b8b3e79ba168 = $S06().Construct();
      parents_f177b45712ba4be0a0d9b8b3e79ba168['Add'](Button_e5d6c10c33654865a62a34ae4a668cf8);
      parents_f177b45712ba4be0a0d9b8b3e79ba168['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_f177b45712ba4be0a0d9b8b3e79ba168['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_f177b45712ba4be0a0d9b8b3e79ba168['Add'](this);
      Button_e5d6c10c33654865a62a34ae4a668cf8['set_Style']($T10().$Cast(StaticResource_a3d0a5d69f4b4b62904fc1311a335c5b['ProvideValue'](new ($T26())(Button_e5d6c10c33654865a62a34ae4a668cf8, null, parents_f177b45712ba4be0a0d9b8b3e79ba168))));
      var parents_a91790ebec7d42df81480fd9a79d9e3f = $S06().Construct();
      parents_a91790ebec7d42df81480fd9a79d9e3f['Add'](Button_e3d0235ab6174d3b85e215ea4b53cd29);
      parents_a91790ebec7d42df81480fd9a79d9e3f['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_a91790ebec7d42df81480fd9a79d9e3f['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_a91790ebec7d42df81480fd9a79d9e3f['Add'](this);
      Button_e3d0235ab6174d3b85e215ea4b53cd29['set_Style']($T10().$Cast(StaticResource_92a23dfbb09a4168a6876dc8682ace34['ProvideValue'](new ($T26())(Button_e3d0235ab6174d3b85e215ea4b53cd29, null, parents_a91790ebec7d42df81480fd9a79d9e3f))));
      var parents_1d4ff1496b11486d82c6aa4197449d42 = $S06().Construct();
      parents_1d4ff1496b11486d82c6aa4197449d42['Add'](Button_1c7279317d4842f7b77e4f49d59d7582);
      parents_1d4ff1496b11486d82c6aa4197449d42['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_1d4ff1496b11486d82c6aa4197449d42['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_1d4ff1496b11486d82c6aa4197449d42['Add'](this);
      Button_1c7279317d4842f7b77e4f49d59d7582['set_Style']($T10().$Cast(StaticResource_25268caf86d4429984d1beeee1322ea9['ProvideValue'](new ($T26())(Button_1c7279317d4842f7b77e4f49d59d7582, null, parents_1d4ff1496b11486d82c6aa4197449d42))));
      var parents_194cc4ef253d4bf7abeeb7dcdbf16ca3 = $S06().Construct();
      parents_194cc4ef253d4bf7abeeb7dcdbf16ca3['Add'](Button_5cfd2939dff04a75adb381bdce3aa11e);
      parents_194cc4ef253d4bf7abeeb7dcdbf16ca3['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_194cc4ef253d4bf7abeeb7dcdbf16ca3['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_194cc4ef253d4bf7abeeb7dcdbf16ca3['Add'](this);
      Button_5cfd2939dff04a75adb381bdce3aa11e['set_Style']($T10().$Cast(StaticResource_f8ddd78fbc2c46e8a0d73b5f55b9cd23['ProvideValue'](new ($T26())(Button_5cfd2939dff04a75adb381bdce3aa11e, null, parents_194cc4ef253d4bf7abeeb7dcdbf16ca3))));
      var parents_c2f225ec561e46928b866763f0c24e9a = $S06().Construct();
      parents_c2f225ec561e46928b866763f0c24e9a['Add'](Button_1790b4a975fa40b7a286a42302e3b71a);
      parents_c2f225ec561e46928b866763f0c24e9a['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_c2f225ec561e46928b866763f0c24e9a['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_c2f225ec561e46928b866763f0c24e9a['Add'](this);
      Button_1790b4a975fa40b7a286a42302e3b71a['set_Style']($T10().$Cast(StaticResource_78cc96e91d67422aa4877a105b577253['ProvideValue'](new ($T26())(Button_1790b4a975fa40b7a286a42302e3b71a, null, parents_c2f225ec561e46928b866763f0c24e9a))));
      var parents_f3e18870278e44f58ad7645a253478d = $S06().Construct();
      parents_f3e18870278e44f58ad7645a253478d['Add'](Button_aff6175a926c4a709d816186efbd641d);
      parents_f3e18870278e44f58ad7645a253478d['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_f3e18870278e44f58ad7645a253478d['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_f3e18870278e44f58ad7645a253478d['Add'](this);
      Button_aff6175a926c4a709d816186efbd641d['set_Style']($T10().$Cast(StaticResource_325ac28614e544e7b1fed8f3d58991bd['ProvideValue'](new ($T26())(Button_aff6175a926c4a709d816186efbd641d, null, parents_f3e18870278e44f58ad7645a253478d))));
      var parents_1c6c53e7719f4faf8aedae710c5d6c42 = $S06().Construct();
      parents_1c6c53e7719f4faf8aedae710c5d6c42['Add'](Button_137d97ae6e5b49a7821b63e4c92edd64);
      parents_1c6c53e7719f4faf8aedae710c5d6c42['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_1c6c53e7719f4faf8aedae710c5d6c42['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_1c6c53e7719f4faf8aedae710c5d6c42['Add'](this);
      Button_137d97ae6e5b49a7821b63e4c92edd64['set_Style']($T10().$Cast(StaticResource_bec170d3bf2b4a2582a69aa255e9f61e['ProvideValue'](new ($T26())(Button_137d97ae6e5b49a7821b63e4c92edd64, null, parents_1c6c53e7719f4faf8aedae710c5d6c42))));
      var parents_f0e0aa5e153a4c9ba6b37b0214fc686b = $S06().Construct();
      parents_f0e0aa5e153a4c9ba6b37b0214fc686b['Add'](Button_1167110c760e469eacf303206edc97a0);
      parents_f0e0aa5e153a4c9ba6b37b0214fc686b['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_f0e0aa5e153a4c9ba6b37b0214fc686b['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_f0e0aa5e153a4c9ba6b37b0214fc686b['Add'](this);
      Button_1167110c760e469eacf303206edc97a0['set_Style']($T10().$Cast(StaticResource_a98bd80c87d34983bd067750d613399b['ProvideValue'](new ($T26())(Button_1167110c760e469eacf303206edc97a0, null, parents_f0e0aa5e153a4c9ba6b37b0214fc686b))));
      var parents_413f588df22642b2a497533f5f03ba55 = $S06().Construct();
      parents_413f588df22642b2a497533f5f03ba55['Add'](Button_2e03f58259104ffd8b87b9c4129cbb47);
      parents_413f588df22642b2a497533f5f03ba55['Add'](Canvas_bec4b478b06a41a6a913089291d95389);
      parents_413f588df22642b2a497533f5f03ba55['Add'](ScrollViewer_756e7e0917c34861b90c3232c63e6466);
      parents_413f588df22642b2a497533f5f03ba55['Add'](this);
      Button_2e03f58259104ffd8b87b9c4129cbb47['set_Style']($T10().$Cast(StaticResource_1dbfff6d86d84143a1b5808f6616c49e['ProvideValue'](new ($T26())(Button_2e03f58259104ffd8b87b9c4129cbb47, null, parents_413f588df22642b2a497533f5f03ba55))));
    }
  };

  function MainPage_OperBtn_Click (sender, e) {
    this['ProcessOperation']((($T0E().$Cast(sender))['get_Name']())['toString']());
  };

  function MainPage_ProcessKey (c) {
    if (this['get_EraseDisplay']()) {
      this['set_Display']($T04().Empty);
      this['set_EraseDisplay'](false);
    }
    this['AddToDisplay'](c);
  };

  function MainPage_ProcessOperation (s) {
    if (s !== null) {
      switch (s) {
        case "BPM": 
          this.LastOper = $T06().Negate;
          this['set_LastValue'](this['get_Display']());
          this['CalcResults']();
          this['set_LastValue'](this['get_Display']());
          this['set_EraseDisplay'](true);
          this.LastOper = $T06().None;
          break;

        case "BDevide": 
          if (this['get_EraseDisplay']()) {
            this.LastOper = $T06().Devide;
          } else {
            this['CalcResults']();
            this.LastOper = $T06().Devide;
            this['set_LastValue'](this['get_Display']());
            this['set_EraseDisplay'](true);
          }
          break;

        case "BMultiply": 
          if (this['get_EraseDisplay']()) {
            this.LastOper = $T06().Multiply;
          } else {
            this['CalcResults']();
            this.LastOper = $T06().Multiply;
            this['set_LastValue'](this['get_Display']());
            this['set_EraseDisplay'](true);
          }
          break;

        case "BMinus": 
          if (this['get_EraseDisplay']()) {
            this.LastOper = $T06().Subtract;
          } else {
            this['CalcResults']();
            this.LastOper = $T06().Subtract;
            this['set_LastValue'](this['get_Display']());
            this['set_EraseDisplay'](true);
          }
          break;

        case "BPlus": 
          if (this['get_EraseDisplay']()) {
            this.LastOper = $T06().Add;
          } else {
            this['CalcResults']();
            this.LastOper = $T06().Add;
            this['set_LastValue'](this['get_Display']());
            this['set_EraseDisplay'](true);
          }
          break;

        case "BEqual": 
          if (!this['get_EraseDisplay']()) {
            this['CalcResults']();
            this['set_EraseDisplay'](true);
            this.LastOper = $T06().None;
            this['set_LastValue'](this['get_Display']());
          }
          break;

        case "BSqrt": 
          this.LastOper = $T06().Sqrt;
          this['set_LastValue'](this['get_Display']());
          this['CalcResults']();
          this['set_LastValue'](this['get_Display']());
          this['set_EraseDisplay'](true);
          this.LastOper = $T06().None;
          break;

        case "BOneOver": 
          this.LastOper = $T06().OneX;
          this['set_LastValue'](this['get_Display']());
          this['CalcResults']();
          this['set_LastValue'](this['get_Display']());
          this['set_EraseDisplay'](true);
          this.LastOper = $T06().None;
          break;

        case "BC": 
          this.LastOper = $T06().None;
          this['set_Display'](this.LastValue = $T04().Empty);
          (this.Paper)['Clear']();
          this['UpdateDisplay']();
          break;

        case "BCE": 
          this.LastOper = $T06().None;
          this['set_Display'](this['get_LastValue']());
          this['UpdateDisplay']();
          break;

      }
    }
  };

  function MainPage_set_Display (value) {
    this._display = value;
  };

  function MainPage_set_EraseDisplay (value) {
    this._erasediplay = value;
  };

  function MainPage_set_LastValue (value) {
    this._last_val = value;
  };

  function MainPage_UpdateDisplay () {
    if ($T04()['IsNullOrEmpty'](this['get_Display']())) {
      (this.DisplayBox)['set_Text']("0");
    } else {
      (this.DisplayBox)['set_Text'](this['get_Display']());
    }
  };

  JSIL.MakeType({
      BaseType: $asm00.TypeRef("Windows.UI.Xaml.Controls.Page"), 
      Name: "SampleCalculatorApp1.MainPage", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      MainPage__ctor
    );

    $.Method({Static:false, Public:false}, "AddToDisplay", 
      JSIL.MethodSignature.Action($.Char), 
      MainPage_AddToDisplay
    );

    $.Method({Static:false, Public:false}, "Calc", 
      new JSIL.MethodSignature($.Double, [$asm07.TypeRef("SampleCalculatorApp1.MainPage+Operation")]), 
      MainPage_Calc
    );

    $.Method({Static:false, Public:false}, "CalcResults", 
      JSIL.MethodSignature.Void, 
      MainPage_CalcResults
    );

    $.Method({Static:false, Public:false}, "CheckResult", 
      JSIL.MethodSignature.Action($.Double), 
      MainPage_CheckResult
    );

    $.Method({Static:false, Public:false}, "DigitBtn_Click", 
      new JSIL.MethodSignature(null, [$.Object, $asm00.TypeRef("Windows.UI.Xaml.RoutedEventArgs")]), 
      MainPage_DigitBtn_Click
    );

    $.Method({Static:false, Public:false}, "get_Display", 
      JSIL.MethodSignature.Return($.String), 
      MainPage_get_Display
    );

    $.Method({Static:false, Public:false}, "get_EraseDisplay", 
      JSIL.MethodSignature.Return($.Boolean), 
      MainPage_get_EraseDisplay
    );

    $.Method({Static:false, Public:false}, "get_LastValue", 
      JSIL.MethodSignature.Return($.String), 
      MainPage_get_LastValue
    );

    $.Method({Static:false, Public:false}, "InitializeComponent", 
      JSIL.MethodSignature.Void, 
      MainPage_InitializeComponent
    );

    $.Method({Static:false, Public:false}, "OperBtn_Click", 
      new JSIL.MethodSignature(null, [$.Object, $asm00.TypeRef("Windows.UI.Xaml.RoutedEventArgs")]), 
      MainPage_OperBtn_Click
    );

    $.Method({Static:false, Public:false}, "ProcessKey", 
      JSIL.MethodSignature.Action($.Char), 
      MainPage_ProcessKey
    );

    $.Method({Static:false, Public:false}, "ProcessOperation", 
      JSIL.MethodSignature.Action($.String), 
      MainPage_ProcessOperation
    );

    $.Method({Static:false, Public:false}, "set_Display", 
      JSIL.MethodSignature.Action($.String), 
      MainPage_set_Display
    );

    $.Method({Static:false, Public:false}, "set_EraseDisplay", 
      JSIL.MethodSignature.Action($.Boolean), 
      MainPage_set_EraseDisplay
    );

    $.Method({Static:false, Public:false}, "set_LastValue", 
      JSIL.MethodSignature.Action($.String), 
      MainPage_set_LastValue
    );

    $.Method({Static:false, Public:false}, "UpdateDisplay", 
      JSIL.MethodSignature.Void, 
      MainPage_UpdateDisplay
    );

    $['Field']({Static:false, Public:false}, "PaperBox", $asm00.TypeRef("Windows.UI.Xaml.Controls.TextBlock")); 
    $['Field']({Static:false, Public:false}, "Paper", $asm07.TypeRef("SampleCalculatorApp1.PaperTrail")); 
    $['Field']({Static:false, Public:false}, "LastOper", $asm07.TypeRef("SampleCalculatorApp1.MainPage+Operation")); 
    $['Field']({Static:false, Public:false}, "_display", $.String); 
    $['Field']({Static:false, Public:false}, "_last_val", $.String); 
    $['Field']({Static:false, Public:false}, "_erasediplay", $.Boolean); 
    $['Field']({Static:false, Public:false}, "DisplayBox", $asm00.TypeRef("Windows.UI.Xaml.Controls.TextBlock")); 
    $['Field']({Static:false, Public:false}, "BC", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BCE", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B7", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B8", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B9", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B4", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B5", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B6", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B1", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B2", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B3", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "B0", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BPeriod", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BDevide", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BMultiply", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BMinus", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BPlus", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BEqual", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BSqrt", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BOneOver", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "BPM", $asm00.TypeRef("Windows.UI.Xaml.Controls.Button")); 
    $['Field']({Static:false, Public:false}, "_contentLoaded", $.Boolean); 
    $.Property({Static:false, Public:false}, "EraseDisplay", $.Boolean);

    $.Property({Static:false, Public:false}, "LastValue", $.String);

    $.Property({Static:false, Public:false}, "Display", $.String);

    $.ImplementInterfaces(
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* enum SampleCalculatorApp1.MainPage+Operation */ 

JSIL.MakeEnum(
  {
    FullName: "SampleCalculatorApp1.MainPage+Operation", 
    BaseType: $asm06.TypeRef("System.Int32"), 
    IsPublic: false, 
    IsFlags: false, 
  }, 
  {
    None: 0, 
    Devide: 1, 
    Multiply: 2, 
    Subtract: 3, 
    Add: 4, 
    Sqrt: 5, 
    OneX: 6, 
    Negate: 7, 
  }
);

JSIL.DeclareNamespace("PreviewOnWinRT");
/* class PreviewOnWinRT.Operation */ 

(function Operation$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm06.System.String)) ();
  };

  function Operation__ctor (name) {
    this['set_Name'](name);
  };

  function Operation_get_Name () {
    return this._name;
  };

  function Operation_set_Name (value) {
    this._name = value;
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Object"), 
      Name: "PreviewOnWinRT.Operation", 
      IsPublic: false, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($.String), 
      Operation__ctor
    );

    $.Method({Static:false, Public:true }, "get_Name", 
      JSIL.MethodSignature.Return($.String), 
      Operation_get_Name
    );

    $.Method({Static:false, Public:true }, "set_Name", 
      JSIL.MethodSignature.Action($.String), 
      Operation_set_Name
    );

    $['Field']({Static:false, Public:false}, "_name", $.String); 
    $.Property({Static:false, Public:true }, "Name", $.String);

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class PreviewOnWinRT.Operations */ 

(function Operations$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm07.PreviewOnWinRT.Operation)) ();
  };

  function Operations__ctor () {
  };

  function Operations_BPlus () {
    return $thisType._BPlus;
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Object"), 
      Name: "PreviewOnWinRT.Operations", 
      IsPublic: false, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      Operations__ctor
    );

    $.Method({Static:true , Public:true }, "BPlus", 
      JSIL.MethodSignature.Return($asm07.TypeRef("PreviewOnWinRT.Operation")), 
      Operations_BPlus
    );

    $['Field']({Static:true , Public:false}, "_BPlus", $asm07.TypeRef("PreviewOnWinRT.Operation")); 
    function Operations__cctor () {
      $thisType._BPlus = new ($T00())("BPlus");
    };


    $.Method({Static:true , Public:false}, ".cctor", 
      JSIL.MethodSignature.Void, 
      Operations__cctor
    );

    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class SampleCalculatorApp1.PaperTrail */ 

(function PaperTrail$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm00.Windows.UI.Xaml.Controls.TextBlock)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm06.System.String)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm06.System.Environment)) ();
  };

  function PaperTrail__ctor$00 () {
  };

  function PaperTrail__ctor$01 (paperBox) {
    this.PaperBox = paperBox;
  };

  function PaperTrail_AddArguments (a) {
    this.args = a;
  };

  function PaperTrail_AddResult (r) {
    var expr_07 = this.PaperBox;
    expr_07['set_Text'](JSIL.ConcatString(expr_07['get_Text'](), $T01()['Format']("{0}={1}{2}", this.args, r, $T02()['get_NewLine']())));
  };

  function PaperTrail_Clear () {
    (this.PaperBox)['set_Text'](this.args = $T01().Empty);
  };

  JSIL.MakeType({
      BaseType: $asm06.TypeRef("System.Object"), 
      Name: "SampleCalculatorApp1.PaperTrail", 
      IsPublic: false, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 1, 
    }, function ($interfaceBuilder) {
    $ = $interfaceBuilder;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      PaperTrail__ctor$00
    );

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Action($asm00.TypeRef("Windows.UI.Xaml.Controls.TextBlock")), 
      PaperTrail__ctor$01
    );

    $.Method({Static:false, Public:true }, "AddArguments", 
      JSIL.MethodSignature.Action($.String), 
      PaperTrail_AddArguments
    );

    $.Method({Static:false, Public:true }, "AddResult", 
      JSIL.MethodSignature.Action($.String), 
      PaperTrail_AddResult
    );

    $.Method({Static:false, Public:true }, "Clear", 
      JSIL.MethodSignature.Void, 
      PaperTrail_Clear
    );

    $['Field']({Static:false, Public:false}, "args", $.String); 
    $['Field']({Static:false, Public:false}, "PaperBox", $asm00.TypeRef("Windows.UI.Xaml.Controls.TextBlock")); 
    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

